name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '💣 Breaking'
    label: 'breaking'
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐞 Bug Fixes'
    label: 'bugfix'
  - title: '👨‍💻 Maintenance'
    label: 'maintenance'
  - title: '📖 Documentation'
    label: 'documentation'
  - title: '🆙 Dependency Updates'
    label: 'dependencies'
  - title: '🚨 Security'
    label: 'security'
    collapse-after: 5

autolabeler:
  - label: 'bugfix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/add/i'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bugfix'
      - 'maintenance'
      - 'documentation'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'
