version: "3.9"
services:
  bot:
    env_file:
      - .env
    build:
      context: .
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      - NETWORK
      - RPC_URL
      - BEACON_RPC_URL
