name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  id-token: write

env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/196690008143/locations/global/workloadIdentityPools/main/providers/github'
  SERVICE_ACCOUNT: 'github@stakestar.iam.gserviceaccount.com'
  IMAGE: 'gcr.io/stakestar/oracle2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider:  ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
      - run: gcloud auth configure-docker
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
